### ISSUE TITLE
怎么在其他lua代码中调用此项目的函数，来运行lisp代码。

### ISSUE THREAD

**Issue by ghost** [andytt/erlisp#1]

**Comment by ertuil** [comment]
本项目的lisp代码并不完备，不和任何lisp兼容，可以说是一个极度简化版本。强烈不建议在正式项目中使用。

确需使用，可以考虑重新封装 erlisp.lua 文件中的相关功能。

**Comment by ghost** [comment]
> 本项目的lisp代码并不完备，不和任何lisp兼容，可以说是一个极度简化版本。强烈不建议在正式项目中使用。
> 
> 确需使用，可以考虑重新封装 erlisp.lua 文件中的相关功能。
能不能不依赖命令行？或是和去掉与特定操作系统有关的，我用的是非标准lua环境，不能用命令行或者特定操作系统相关的。

**Comment by ghost** [comment]
> 本项目的lisp代码并不完备，不和任何lisp兼容，可以说是一个极度简化版本。强烈不建议在正式项目中使用。
> 
> 确需使用，可以考虑重新封装 erlisp.lua 文件中的相关功能。

那个load_lisp函数的ENV参数是什么

**Comment by ghost** [comment]
> 本项目的lisp代码并不完备，不和任何lisp兼容，可以说是一个极度简化版本。强烈不建议在正式项目中使用。
> 
> 确需使用，可以考虑重新封装 erlisp.lua 文件中的相关功能。

还有，哪个是运行lisp代码的函数。
